# Generated by Django 6.0.6 on 2026-06-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='match_score',
            field=models.IntegerField(default=0),
        ),
    ]
